Added Support for OptionsList Type.
bby-stdc/SwiftTweaks pull request #1
Opened 2017-02-14 01:57 UTC by Priyatham51

2017-02-14 18:59 UTC, asilkey1 commented on SwiftTweaks/TweakPersistency.swift
> +        case .optionsList: return "optionsList"
Minor: Please fix the indentation.

2017-02-14 18:59 UTC, asilkey1 commented on SwiftTweaks/TweakStore.swift
> +        case let .optionsList(defaultValue: defaultValue, options: options):
Minor: Please fix the indentation.

2017-02-14 19:06 UTC, asilkey1 commented on SwiftTweaks/TweakTableCell.swift
> +    private static let optionsListWidthFraction: CGFloat = 0.60
Minor: Please fix the indentation.

2017-02-14 19:08 UTC, asilkey1 approved these changes

2017-02-14 19:26 UTC, rehatBB approved these changes

2017-02-14 21:37 UTC, mikedavis-bby commented on SwiftTweaks/Tweak.swift
> +            defaultValue: StringOption(value: defaultValue ?? options.first!),
options will never be []    ?

2017-02-14 22:17 UTC, mikedavis-bby commented on SwiftTweaks/TweakTableCell.swift
> +            disclosureArrow.isHidden = true
very minor: helpful to keep all of these in same order for each case.

2017-02-14 22:19 UTC, mikedavis-bby commented on SwiftTweaks/TweakTableCell.swift
>  			assertionFailure("Shouldn't be able to update text field with a Color or Boolean tweak.")
minor: ..or OptionsList tweak

2017-02-14 22:27 UTC, mikedavis-bby approved these changes

2017-02-17 00:09 UTC, anilmanukonda requested changes

2017-02-17 00:09 UTC, anilmanukonda commented on SwiftTweaks/Tweak.swift
> +                                options: options!.map{ $0 as! StringOption}
guard options before mapping

2017-02-17 00:09 UTC, anilmanukonda commented on SwiftTweaks/TweakTableCell.swift
> +    private let doneButton = UIBarButtonItem(title: "Done TT", style: .done, target: nil, action: nil)
Why is this "Done TT" ?

2017-02-17 00:09 UTC, anilmanukonda commented on SwiftTweaks/TweakTableCell.swift
> +    private let doneButton = UIBarButtonItem(title: "Done TT", style: .done, target: nil, action: nil)
Also how can I change these button targets?

2017-02-17 00:09 UTC, anilmanukonda commented on SwiftTweaks/TweakTableCell.swift
> +        return 1
This might serve our purpose but if we want to contribute back to the library, we have to make this configurable

2017-02-17 00:09 UTC, anilmanukonda commented on SwiftTweaks/TweakViewData.swift
> +            self = .optionsList(value: value as! StringOption, defaultValue: defaultValue as! StringOption, options: options!.map{ $0 as! StringOption })
Fix force casting

2017-02-17 00:46 UTC, Priyatham51 commented on SwiftTweaks/TweakViewData.swift
> +            self = .optionsList(value: value as! StringOption, defaultValue: defaultValue as! StringOption, options: options!.map{ $0 as! StringOption })
Just following the style in the SDK. I don't want it to introduce `guard` statements.

2017-02-17 00:47 UTC, Priyatham51 commented on SwiftTweaks/TweakTableCell.swift
> +    private let doneButton = UIBarButtonItem(title: "Done TT", style: .done, target: nil, action: nil)
You cannot change the button target. You should bind to these tweaks. So you get notified when there is a change in a tweaks value.

2017-02-17 00:49 UTC, Priyatham51 commented on SwiftTweaks/Tweak.swift
> +            defaultValue: StringOption(value: defaultValue ?? options.first!),
It can/should never be nil if `optionsList` type is used. We have  precondition during initialization.

2017-02-17 04:34 UTC, Priyatham51 commented on SwiftTweaks/Tweak.swift
> +                                options: options!.map{ $0 as! StringOption}
One can never create a `OptionsList` `TweakType` with a nil. We have a `precondition` in `public` init. So I don't see a value in adding guard here.

2017-02-17 04:34 UTC, Priyatham51 commented on SwiftTweaks/TweakViewData.swift
> +            self = .optionsList(value: value as! StringOption, defaultValue: defaultValue as! StringOption, options: options!.map{ $0 as! StringOption })
Will add a precondition here. I also just realized that this is marked as `internal`. So there should be no issues with force unwrap

2017-03-02 20:17 UTC, merged